name: APT repo publish

on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  packages: read
  
jobs:
  build:
    name: Build deb
    runs-on: ubuntu-latest
    env:
      APP_NAME: 'whatstheweather'
      BUILD_ARCH: 'amd64'

    steps:
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        name: build
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: ci.yml
        commit: ${{ vars.GITHUB_SHA }}
        path: output
        search_artifacts: true

    - name: Create deb
      run: |
        REF=${{ github.ref_name }}
        APP_VERSION=${REF//v/}
        APP_ID=${{ env.APP_NAME }}_${APP_VERSION}_${{ env.BUILD_ARCH }}
        TMP_DIR=/tmp/$APP_ID
        APP_DIR=$TMP_DIR/usr/local/bin
        mkdir -p $APP_DIR
        cp output/${{ env.APP_NAME }} $APP_DIR
        mkdir $TMP_DIR/DEBIAN
        
        cat <<EOF > $TMP_DIR/DEBIAN/control
        Package: ${{ env.APP_NAME }}
        Version: $APP_VERSION
        Architecture: ${{ env.BUILD_ARCH }}
        Maintainer: Dominik Zarsky <dzarsky@dzarsky.eu>
        Description: A tool for displaying weather forecast in the command line.
        EOF

        dpkg-deb --build --root-owner-group $TMP_DIR

    - name: Publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: deb
        path: |
          /tmp/*.deb
